### ISSUE TITLE
Make this installable from npm repo

### ISSUE THREAD

**Issue by keiono** [biothings/biothings_client.js#1]
It is useful if I can install this library from npm.  It is ideal if you can rename this library from biothings_client to biothings-client because it is more standard naming scheme for npm packages. 

Then I can install by:

```npm install biothings-client --save```

**Comment by ben-abraham** [comment]
Created the package in npm under the name biothings_client, so it can be installed just like you specified (just an _ instead of -)
Tested installing/loading/testing in a new directory from npm and it worked just fine for me.

**Comment by ben-abraham** [comment]
Added you as an owner on the npm package.
