### ISSUE TITLE
Final changes

### ISSUE THREAD

**Issue by ben-abraham** [biothings/biothings_client.js#2]
Not sure if you saw the post on codersclan, but I had this update.

Alright, I committed the change so that it checks if its running under browser and doesn't set the useragent if so.

Also, for embedding the libraries into the packed, its doable, however when using browserify with axios it was using the /dist/ version of the axios library, which doesn't support running directly under node, as it uses the XMLHTTPRequest library under the hood which is for browser support. If this is fine (aka. intended use of the packaged dist/ files is just for browser only), then it should work. It also increases the output sizes from 16/13 KB (normal/min) to 968/280KB

**Comment by newgene** [comment]
@ben-abraham thanks for the update. There are a few factors can be considered:

* Under node, I assume people will use this package via "npm install biothings-client". Will the node code import the bundled js file or the individual js files under the folder? 

* If under node, the bundled js file under /dist is not used, means that only browser will use the bundled file, then I think it's fine just make bundled file work under the browser.

* When creating a bundled file for the browser, I assume that 968/280KB file includes every dependency (axios, rxjs, etc). Can we leave them out and load dependencies separately from "<script>" tag? E.g. each one can be loaded from unpkg URLs.

Finally, I feel that this cross nodejs and browser compatibility issue should be a common problem, is there a common good practice or an example from a well-known package we can use? I'm comfortable with whatever the "common" way of doing this, but I'm just not familiar with the nodejs to tell what is the right solution.

**Comment by newgene** [comment]
Also, since we can detect whether the package is running under node or browser, can we modify our code to make it work nicely on both? For example, when under browser, we assume axios and rxjs have already been loaded before biothings_client.

**Comment by ben-abraham** [comment]
- require('biothings_client') will load whats specified in the package.json file, which is client.js, so not the dist/version
- Ok
- Yes, that's all the dependencies. I can try getting requirejs to work well with just the <script> tags, but I was having a lot of difficulty with it before, I'll spend a bit more time to see if I can find a cleaner way of implementing it.

And I don't think we will need to do browser detection (aside from the user-agent check) since browserify will be using the dist/ version which appears to be intended for web browsers.

**Comment by ben-abraham** [comment]
I'm still looking into the browser testing, its proving quite difficult because most of the packages/dependencies that are being used don't define a module name when loaded from a <script> tag directly ([more info](http://requirejs.org/docs/errors.html#mismatch))
So far the best I've been able to do starting fresh, is essentially the same solution, but I was able to reduce the require.config() line and get rid of the packages section in place of a cleaner lines in the paths config. This is what it looks like now

  ```
  requirejs.config({
      nodeRequire: require,
      paths: {
        'axios': 'https://cdnjs.cloudflare.com/ajax/libs/axios/0.16.2/axios',
        '@reactivex/rxjs': 'https://unpkg.com/@reactivex/rxjs@5.5.2/dist/global/Rx',
        'mocha': 'https://cdnjs.cloudflare.com/ajax/libs/mocha/4.0.1/mocha',
        'chai': 'https://cdnjs.cloudflare.com/ajax/libs/chai/4.1.2/chai',
        'biothings_client': 'dist/biothings_client',
        'gene_test': 'test/gene',
        'variant_test': 'test/variant'
      },
      shim: {
        'biothings_client': {
          deps: ['axios', 'extend', '@reactivex/rxjs', 'assert'],
          exports: 'biothings_client'
        },
        '../client': {
          deps: ['biothings_client'],
          exports: '../client'
        },
        'gene_test': {
          deps: ['biothings_client', 'mocha', '../client'],
          exports: 'gene_test'
        },
        'variant_test': {
          deps: ['biothings_client', 'mocha', '../client'],
          exports: 'variant_test'
        }
      }
    })
```

Pretty much the rest of the file is identical.

**Comment by newgene** [comment]
@ben-abraham thanks! This requirejs.config looks a bit cleaner to me. You can update the test.html. 

Yeah, I'm convinced that making nodejs "require" work with html "<script>" tag is hard. Users who want to use biothings_client module in browser, should use something like browserify or webpack to make the bundled js file for their web app (including any other modules they use).

**Comment by ben-abraham** [comment]
Alright, I committed those changes to test.html.
